import { Book } from './schema';

export const demoBooks: Book[] = [
  {
    id: 1,
    title: "The Silent Patient",
    author: "Alex Michaelides",
    description: "Alicia Berenson's life is seemingly perfect. A famous painter married to an in-demand fashion photographer, she lives in a grand house with big windows overlooking a park in one of London's most desirable areas. One evening her husband Gabriel returns home late from a fashion shoot, and Alicia shoots him five times in the face, and then never speaks another word.",
    price: "16.99",
    imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    category: "Fiction",
    stock: 12,
    rating: "4.5",
    reviewCount: 128,
    featured: true,
    newRelease: false
  },
  {
    id: 2,
    title: "Becoming",
    author: "Michelle Obama",
    description: "In her memoir, a work of deep reflection and mesmerizing storytelling, Michelle Obama invites readers into her world, chronicling the experiences that have shaped her—from her childhood on the South Side of Chicago to her years as an executive balancing the demands of motherhood and work, to her time spent at the world's most famous address.",
    price: "19.99",
    imageUrl: "https://images.unsplash.com/photo-1531928351158-2f736078e0a1?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    category: "Non-Fiction",
    stock: 8,
    rating: "5.0",
    reviewCount: 245,
    featured: true,
    newRelease: false
  },
  {
    id: 3,
    title: "Dune",
    author: "Frank Herbert",
    description: "Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world where the only thing of value is the \"spice\" melange, a drug capable of extending life and enhancing consciousness. Coveted across the known universe, melange is a prize worth killing for...",
    price: "14.99",
    imageUrl: "https://images.unsplash.com/photo-1529590003495-b2646e2718bf?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    category: "Science Fiction",
    stock: 25,
    rating: "4.0",
    reviewCount: 184,
    featured: true,
    newRelease: false
  },
  {
    id: 4,
    title: "The Guest List",
    author: "Lucy Foley",
    description: "On an island off the coast of Ireland, guests gather to celebrate two people joining their lives together as one. The groom: handsome and charming, a rising television star. The bride: smart and ambitious, a magazine publisher. It's a wedding for a magazine, or for a celebrity: the designer dress, the remote location, the luxe party favors, the boutique whiskey. The cell phone service may be spotty and the waves may be rough, but every detail has been expertly planned and will be expertly executed.",
    price: "15.99",
    imageUrl: "https://images.unsplash.com/photo-1610882648335-ced8fc8fa6b6?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    category: "Mystery",
    stock: 5,
    rating: "4.5",
    reviewCount: 97,
    featured: true,
    newRelease: false
  },
  {
    id: 5,
    title: "The Midnight Library",
    author: "Matt Haig",
    description: "Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived. To see how things would be if you had made other choices... Would you have done anything different, if you had the chance to undo your regrets?",
    price: "18.99",
    imageUrl: "https://images.unsplash.com/photo-1603162525937-96a3b880cb50?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    category: "Fiction",
    stock: 15,
    rating: "5.0",
    reviewCount: 42,
    featured: false,
    newRelease: true
  },
  {
    id: 6,
    title: "The Push",
    author: "Ashley Audrain",
    description: "A tense, page-turning psychological drama about the making and breaking of a family—and a woman whose experience of motherhood is nothing at all what she hoped for—and everything she feared.",
    price: "17.99",
    imageUrl: "https://images.unsplash.com/photo-1604987051276-89c1ee3720c3?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    category: "Mystery",
    stock: 9,
    rating: "4.0",
    reviewCount: 28,
    featured: false,
    newRelease: true
  },
  {
    id: 7,
    title: "A Promised Land",
    author: "Barack Obama",
    description: "In the stirring, highly anticipated first volume of his presidential memoirs, Barack Obama tells the story of his improbable odyssey from young man searching for his identity to leader of the free world, describing in strikingly personal detail both his political education and the landmark moments of the first term of his historic presidency—a time of dramatic transformation and turmoil.",
    price: "24.99",
    imageUrl: "https://images.unsplash.com/photo-1541963463532-d68292c34b19?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    category: "Biography",
    stock: 18,
    rating: "4.5",
    reviewCount: 76,
    featured: false,
    newRelease: true
  },
  {
    id: 8,
    title: "Project Hail Mary",
    author: "Andy Weir",
    description: "Ryland Grace is the sole survivor on a desperate, last-chance mission—and if he fails, humanity and the earth itself will perish. Except that right now, he doesn't know that. He can't even remember his own name, let alone the nature of his assignment or how to complete it.",
    price: "21.99",
    imageUrl: "https://images.unsplash.com/photo-1625895197185-efcec01cffe0?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    category: "Fantasy",
    stock: 7,
    rating: "5.0",
    reviewCount: 54,
    featured: false,
    newRelease: true
  },
  {
    id: 9,
    title: "The Four Winds",
    author: "Kristin Hannah",
    description: "From the #1 New York Times bestselling author of The Nightingale and The Great Alone comes an epic novel of love and heroism and hope, set against the backdrop of one of America's most defining eras—the Great Depression.",
    price: "19.99",
    imageUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    category: "Historical Fiction",
    stock: 14,
    rating: "4.7",
    reviewCount: 112,
    featured: true,
    newRelease: false
  },
  {
    id: 10,
    title: "Educated",
    author: "Tara Westover",
    description: "Born to survivalists in the mountains of Idaho, Tara Westover was seventeen the first time she set foot in a classroom. Her family was so isolated from mainstream society that there was no one to ensure the children received an education, and no one to intervene when one of Tara's older brothers became violent.",
    price: "18.99",
    imageUrl: "https://images.unsplash.com/photo-1511108690759-009324a90311?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    category: "Non-Fiction",
    stock: 22,
    rating: "4.8",
    reviewCount: 156,
    featured: true,
    newRelease: false
  },
  {
    id: 11,
    title: "Where the Crawdads Sing",
    author: "Delia Owens",
    description: "For years, rumors of the 'Marsh Girl' have haunted Barkley Cove, a quiet town on the North Carolina coast. So in late 1969, when handsome Chase Andrews is found dead, the locals immediately suspect Kya Clark, the so-called Marsh Girl.",
    price: "16.99",
    imageUrl: "https://images.unsplash.com/photo-1598454444604-28ef4ae003ae?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    category: "Fiction",
    stock: 19,
    rating: "4.8",
    reviewCount: 186,
    featured: true,
    newRelease: false
  },
  {
    id: 12,
    title: "Circe",
    author: "Madeline Miller",
    description: "In the house of Helios, god of the sun and mightiest of the Titans, a daughter is born. But Circe is a strange child—not powerful, like her father, nor viciously alluring like her mother. Turning to the world of mortals for companionship, she discovers that she does possess power—the power of witchcraft, which can transform rivals into monsters and menace the gods themselves.",
    price: "17.99",
    imageUrl: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    category: "Fantasy",
    stock: 15,
    rating: "4.6",
    reviewCount: 97,
    featured: true,
    newRelease: false
  },
  {
    id: 13,
    title: "The Invisible Life of Addie LaRue",
    author: "V.E. Schwab",
    description: "A Life No One Will Remember. A Story You Will Never Forget. France, 1714: in a moment of desperation, a young woman makes a Faustian bargain to live forever—and is cursed to be forgotten by everyone she meets.",
    price: "19.99",
    imageUrl: "https://images.unsplash.com/photo-1521714161819-15534968fc5f?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    category: "Fantasy",
    stock: 10,
    rating: "4.9",
    reviewCount: 68,
    featured: false,
    newRelease: true
  },
  {
    id: 14,
    title: "The Vanishing Half",
    author: "Brit Bennett",
    description: "The Vignes twin sisters will always be identical. But after growing up together in a small, southern black community and running away at age sixteen, it's not just the shape of their daily lives that is different as adults, it's everything: their families, their communities, their racial identities.",
    price: "18.99",
    imageUrl: "https://images.unsplash.com/photo-1610882825717-75f92f41352e?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    category: "Historical Fiction",
    stock: 12,
    rating: "4.7",
    reviewCount: 72,
    featured: false,
    newRelease: true
  },
  {
    id: 15,
    title: "Mexican Gothic",
    author: "Silvia Moreno-Garcia",
    description: "After receiving a frantic letter from her newly-wed cousin begging for someone to save her from a mysterious doom, Noemí Taboada heads to High Place, a distant house in the Mexican countryside.",
    price: "15.99",
    imageUrl: "https://images.unsplash.com/photo-1621351183012-e2f9972dd9bf?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    category: "Horror",
    stock: 8,
    rating: "4.2",
    reviewCount: 49,
    featured: false,
    newRelease: true
  },
  {
    id: 16,
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    description: "100,000 years ago, at least six human species inhabited the earth. Today there is just one. Us. Homo sapiens. How did our species succeed in the battle for dominance? Why did our foraging ancestors come together to create cities and kingdoms?",
    price: "22.99",
    imageUrl: "https://images.unsplash.com/photo-1532012197267-da84d127e765?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    category: "Non-Fiction",
    stock: 24,
    rating: "4.8",
    reviewCount: 215,
    featured: true,
    newRelease: false
  },
  {
    id: 17,
    title: "The Song of Achilles",
    author: "Madeline Miller",
    description: "Greece in the age of heroes. Patroclus, an awkward young prince, has been exiled to the court of King Peleus and his perfect son Achilles. By all rights their paths should never cross, but Achilles takes the shamed prince as his friend, and as they grow into young men skilled in the arts of war and medicine, their bond blossoms into something deeper.",
    price: "16.99",
    imageUrl: "https://images.unsplash.com/photo-1629992101753-56d196c8aabb?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    category: "Historical Fiction",
    stock: 18,
    rating: "4.9",
    reviewCount: 92,
    featured: true,
    newRelease: false
  },
  {
    id: 18,
    title: "Klara and the Sun",
    author: "Kazuo Ishiguro",
    description: "From the bestselling and Booker Prize-winning author of 'Never Let Me Go' and 'The Remains of the Day', a stunning new novel that asks, what does it mean to love?",
    price: "20.99",
    imageUrl: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    category: "Science Fiction",
    stock: 11,
    rating: "4.3",
    reviewCount: 58,
    featured: false,
    newRelease: true
  },
  {
    id: 19,
    title: "The Alchemist",
    author: "Paulo Coelho",
    description: "Paulo Coelho's masterpiece tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. His quest will lead him to riches far different—and far more satisfying—than he ever imagined.",
    price: "14.99",
    imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    category: "Fiction",
    stock: 30,
    rating: "4.7",
    reviewCount: 325,
    featured: true,
    newRelease: false
  },
  {
    id: 20,
    title: "The Thursday Murder Club",
    author: "Richard Osman",
    description: "In a peaceful retirement village, four unlikely friends meet weekly in the Jigsaw Room to discuss unsolved crimes; together they call themselves The Thursday Murder Club.",
    price: "16.99",
    imageUrl: "https://images.unsplash.com/photo-1621351183012-e2f9972dd9bf?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    category: "Mystery",
    stock: 14,
    rating: "4.5",
    reviewCount: 67,
    featured: false,
    newRelease: true
  }
];

export const categories = [
  "All",
  "Fiction",
  "Non-Fiction",
  "Science Fiction",
  "Mystery",
  "Biography",
  "History",
  "Fantasy",
  "Horror",
  "Historical Fiction"
];